//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>About Page</summary>
	[PublishedModel("aboutPage")]
	public partial class AboutPage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "aboutPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<AboutPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public AboutPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Ceo - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CeoImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ceoImage");

		///<summary>
		/// Ceo - Image Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoImageTitle")]
		public virtual string CeoImageTitle => this.Value<string>(_publishedValueFallback, "ceoImageTitle");

		///<summary>
		/// Ceo - Info Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoInfoTitle")]
		public virtual string CeoInfoTitle => this.Value<string>(_publishedValueFallback, "ceoInfoTitle");

		///<summary>
		/// Ceo - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString CeoText => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "ceoText");

		///<summary>
		/// Contact - Background Image One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBackgroundImageOne")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactBackgroundImageOne => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactBackgroundImageOne");

		///<summary>
		/// Contact - Background Image Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBackgroundImageTwo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactBackgroundImageTwo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactBackgroundImageTwo");

		///<summary>
		/// Contact - Box One Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxOneText")]
		public virtual string ContactBoxOneText => this.Value<string>(_publishedValueFallback, "contactBoxOneText");

		///<summary>
		/// Contact - Box One Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxOneTitle")]
		public virtual string ContactBoxOneTitle => this.Value<string>(_publishedValueFallback, "contactBoxOneTitle");

		///<summary>
		/// Contact - Box Three Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxThreeText")]
		public virtual string ContactBoxThreeText => this.Value<string>(_publishedValueFallback, "contactBoxThreeText");

		///<summary>
		/// Contact - Box Three Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxThreeTitle")]
		public virtual string ContactBoxThreeTitle => this.Value<string>(_publishedValueFallback, "contactBoxThreeTitle");

		///<summary>
		/// Contact - Box Two Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxTwoText")]
		public virtual string ContactBoxTwoText => this.Value<string>(_publishedValueFallback, "contactBoxTwoText");

		///<summary>
		/// Contact - Box Two Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxTwoTitle")]
		public virtual string ContactBoxTwoTitle => this.Value<string>(_publishedValueFallback, "contactBoxTwoTitle");

		///<summary>
		/// Contact - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactHeadline")]
		public virtual string ContactHeadline => this.Value<string>(_publishedValueFallback, "contactHeadline");

		///<summary>
		/// Contact - Main Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactMainImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactMainImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactMainImage");

		///<summary>
		/// Experts - Card Five Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardFiveImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ExpertsCardFiveImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "expertsCardFiveImage");

		///<summary>
		/// Experts - Card Five Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardFiveText")]
		public virtual string ExpertsCardFiveText => this.Value<string>(_publishedValueFallback, "expertsCardFiveText");

		///<summary>
		/// Experts - Card Five Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardFiveTitle")]
		public virtual string ExpertsCardFiveTitle => this.Value<string>(_publishedValueFallback, "expertsCardFiveTitle");

		///<summary>
		/// Experts - Card Four Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardFourImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ExpertsCardFourImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "expertsCardFourImage");

		///<summary>
		/// Experts - Card Four Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardFourText")]
		public virtual string ExpertsCardFourText => this.Value<string>(_publishedValueFallback, "expertsCardFourText");

		///<summary>
		/// Experts - Card Four Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardFourTitle")]
		public virtual string ExpertsCardFourTitle => this.Value<string>(_publishedValueFallback, "expertsCardFourTitle");

		///<summary>
		/// Experts - Card One Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardOneImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ExpertsCardOneImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "expertsCardOneImage");

		///<summary>
		/// Experts - Card One Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardOneText")]
		public virtual string ExpertsCardOneText => this.Value<string>(_publishedValueFallback, "expertsCardOneText");

		///<summary>
		/// Experts - Card One Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardOneTitle")]
		public virtual string ExpertsCardOneTitle => this.Value<string>(_publishedValueFallback, "expertsCardOneTitle");

		///<summary>
		/// Experts - Card Seven Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardSevenImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ExpertsCardSevenImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "expertsCardSevenImage");

		///<summary>
		/// Experts - Card Seven Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardSevenText")]
		public virtual string ExpertsCardSevenText => this.Value<string>(_publishedValueFallback, "expertsCardSevenText");

		///<summary>
		/// Experts - Card Seven Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardSevenTitle")]
		public virtual string ExpertsCardSevenTitle => this.Value<string>(_publishedValueFallback, "expertsCardSevenTitle");

		///<summary>
		/// Experts - Card Six Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardSixImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ExpertsCardSixImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "expertsCardSixImage");

		///<summary>
		/// Experts - Card Six Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardSixText")]
		public virtual string ExpertsCardSixText => this.Value<string>(_publishedValueFallback, "expertsCardSixText");

		///<summary>
		/// Experts - Card Six Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardSixTitle")]
		public virtual string ExpertsCardSixTitle => this.Value<string>(_publishedValueFallback, "expertsCardSixTitle");

		///<summary>
		/// Experts - Card Three Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardThreeImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ExpertsCardThreeImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "expertsCardThreeImage");

		///<summary>
		/// Experts - Card Three Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardThreeText")]
		public virtual string ExpertsCardThreeText => this.Value<string>(_publishedValueFallback, "expertsCardThreeText");

		///<summary>
		/// Experts - Card Three Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardThreeTitle")]
		public virtual string ExpertsCardThreeTitle => this.Value<string>(_publishedValueFallback, "expertsCardThreeTitle");

		///<summary>
		/// Experts - Card Two Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardTwoImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ExpertsCardTwoImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "expertsCardTwoImage");

		///<summary>
		/// Experts - Card Two Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardTwoText")]
		public virtual string ExpertsCardTwoText => this.Value<string>(_publishedValueFallback, "expertsCardTwoText");

		///<summary>
		/// Experts - Card Two Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsCardTwoTitle")]
		public virtual string ExpertsCardTwoTitle => this.Value<string>(_publishedValueFallback, "expertsCardTwoTitle");

		///<summary>
		/// Experts - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsHeadline")]
		public virtual string ExpertsHeadline => this.Value<string>(_publishedValueFallback, "expertsHeadline");

		///<summary>
		/// Experts - Section Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expertsSectionTitle")]
		public virtual string ExpertsSectionTitle => this.Value<string>(_publishedValueFallback, "expertsSectionTitle");

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// Page Title - Breadcrumb Current Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleBreadcrumbCurrentText")]
		public virtual string PageTitleBreadcrumbCurrentText => this.Value<string>(_publishedValueFallback, "pageTitleBreadcrumbCurrentText");

		///<summary>
		/// Page Title - Breadcrumb Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleBreadcrumbText")]
		public virtual string PageTitleBreadcrumbText => this.Value<string>(_publishedValueFallback, "pageTitleBreadcrumbText");

		///<summary>
		/// Page Title - Breadcrumb Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleBreadcrumbUrl")]
		public virtual string PageTitleBreadcrumbUrl => this.Value<string>(_publishedValueFallback, "pageTitleBreadcrumbUrl");

		///<summary>
		/// Page Title - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleHeadline")]
		public virtual string PageTitleHeadline => this.Value<string>(_publishedValueFallback, "pageTitleHeadline");

		///<summary>
		/// Reviews - Company
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsCompany")]
		public virtual string ReviewsCompany => this.Value<string>(_publishedValueFallback, "reviewsCompany");

		///<summary>
		/// Reviews - Employee Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsEmployeeImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ReviewsEmployeeImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "reviewsEmployeeImage");

		///<summary>
		/// Reviews - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsHeadline")]
		public virtual string ReviewsHeadline => this.Value<string>(_publishedValueFallback, "reviewsHeadline");

		///<summary>
		/// Reviews - Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsName")]
		public virtual string ReviewsName => this.Value<string>(_publishedValueFallback, "reviewsName");

		///<summary>
		/// Reviews - Section Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsSectionTitle")]
		public virtual string ReviewsSectionTitle => this.Value<string>(_publishedValueFallback, "reviewsSectionTitle");

		///<summary>
		/// Reviews - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsText")]
		public virtual string ReviewsText => this.Value<string>(_publishedValueFallback, "reviewsText");
	}
}
