//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Annual Report for Juva Inc.</summary>
	[PublishedModel("annualReportForJuvaInc")]
	public partial class AnnualReportForJuvaInc : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "annualReportForJuvaInc";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<AnnualReportForJuvaInc, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public AnnualReportForJuvaInc(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Article One - Bulleted Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleOneBulletedText")]
		public virtual string ArticleOneBulletedText => this.Value<string>(_publishedValueFallback, "articleOneBulletedText");

		///<summary>
		/// Article One - Bulleted Text Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleOneBulletedTextThree")]
		public virtual string ArticleOneBulletedTextThree => this.Value<string>(_publishedValueFallback, "articleOneBulletedTextThree");

		///<summary>
		/// Article One - Bulleted Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleOneBulletedTextTwo")]
		public virtual string ArticleOneBulletedTextTwo => this.Value<string>(_publishedValueFallback, "articleOneBulletedTextTwo");

		///<summary>
		/// Article One - Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleOneDate")]
		public virtual string ArticleOneDate => this.Value<string>(_publishedValueFallback, "articleOneDate");

		///<summary>
		/// Article One - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleOneImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ArticleOneImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "articleOneImage");

		///<summary>
		/// Article One - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleOneTitle")]
		public virtual string ArticleOneTitle => this.Value<string>(_publishedValueFallback, "articleOneTitle");

		///<summary>
		/// Article One - Title Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleOneTitleTwo")]
		public virtual string ArticleOneTitleTwo => this.Value<string>(_publishedValueFallback, "articleOneTitleTwo");

		///<summary>
		/// Article Three - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleThreeImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ArticleThreeImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "articleThreeImage");

		///<summary>
		/// Article Three - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleThreeText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ArticleThreeText => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "articleThreeText");

		///<summary>
		/// Article Three - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleThreeTitle")]
		public virtual string ArticleThreeTitle => this.Value<string>(_publishedValueFallback, "articleThreeTitle");

		///<summary>
		/// Article Two - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleTwoImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ArticleTwoImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "articleTwoImage");

		///<summary>
		/// Article Two - Side Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleTwoSideText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ArticleTwoSideText => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "articleTwoSideText");

		///<summary>
		/// Article Two - Side Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleTwoSideTitle")]
		public virtual string ArticleTwoSideTitle => this.Value<string>(_publishedValueFallback, "articleTwoSideTitle");

		///<summary>
		/// Article Two - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleTwoText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ArticleTwoText => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "articleTwoText");

		///<summary>
		/// Article Two - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleTwoTitle")]
		public virtual string ArticleTwoTitle => this.Value<string>(_publishedValueFallback, "articleTwoTitle");

		///<summary>
		/// Aside Contact - Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideContactBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AsideContactBackgroundImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "asideContactBackgroundImage");

		///<summary>
		/// Aside Contact - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideContactText")]
		public virtual string AsideContactText => this.Value<string>(_publishedValueFallback, "asideContactText");

		///<summary>
		/// Aside Contact - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideContactTitle")]
		public virtual string AsideContactTitle => this.Value<string>(_publishedValueFallback, "asideContactTitle");

		///<summary>
		/// Aside Project - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideProjectTitle")]
		public virtual string AsideProjectTitle => this.Value<string>(_publishedValueFallback, "asideProjectTitle");

		///<summary>
		/// Aside Tags - Tag Eight
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideTagsTagEight")]
		public virtual string AsideTagsTagEight => this.Value<string>(_publishedValueFallback, "asideTagsTagEight");

		///<summary>
		/// Aside Tags - Tag Five
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideTagsTagFive")]
		public virtual string AsideTagsTagFive => this.Value<string>(_publishedValueFallback, "asideTagsTagFive");

		///<summary>
		/// Aside Tags - Tag Four
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideTagsTagFour")]
		public virtual string AsideTagsTagFour => this.Value<string>(_publishedValueFallback, "asideTagsTagFour");

		///<summary>
		/// Aside Tags - Tag One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideTagsTagOne")]
		public virtual string AsideTagsTagOne => this.Value<string>(_publishedValueFallback, "asideTagsTagOne");

		///<summary>
		/// Aside Tags - Tag Seven
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideTagsTagSeven")]
		public virtual string AsideTagsTagSeven => this.Value<string>(_publishedValueFallback, "asideTagsTagSeven");

		///<summary>
		/// Aside Tags - Tag Six
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideTagsTagSix")]
		public virtual string AsideTagsTagSix => this.Value<string>(_publishedValueFallback, "asideTagsTagSix");

		///<summary>
		/// Aside Tags - Tag Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideTagsTagThree")]
		public virtual string AsideTagsTagThree => this.Value<string>(_publishedValueFallback, "asideTagsTagThree");

		///<summary>
		/// Aside Tags - Tag Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideTagsTagTwo")]
		public virtual string AsideTagsTagTwo => this.Value<string>(_publishedValueFallback, "asideTagsTagTwo");

		///<summary>
		/// Aside Tags - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideTagsTitle")]
		public virtual string AsideTagsTitle => this.Value<string>(_publishedValueFallback, "asideTagsTitle");

		///<summary>
		/// Card Four - Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cardFourDate")]
		public virtual string CardFourDate => this.Value<string>(_publishedValueFallback, "cardFourDate");

		///<summary>
		/// Card Four - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cardFourImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CardFourImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "cardFourImage");

		///<summary>
		/// Card Four - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cardFourTitle")]
		public virtual string CardFourTitle => this.Value<string>(_publishedValueFallback, "cardFourTitle");

		///<summary>
		/// Card One - Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cardOneDate")]
		public virtual string CardOneDate => this.Value<string>(_publishedValueFallback, "cardOneDate");

		///<summary>
		/// Card One - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cardOneImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CardOneImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "cardOneImage");

		///<summary>
		/// Card One - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cardOneTitle")]
		public virtual string CardOneTitle => this.Value<string>(_publishedValueFallback, "cardOneTitle");

		///<summary>
		/// Card Three - Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cardThreeDate")]
		public virtual string CardThreeDate => this.Value<string>(_publishedValueFallback, "cardThreeDate");

		///<summary>
		/// Card Three - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cardThreeImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CardThreeImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "cardThreeImage");

		///<summary>
		/// Card Three - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cardThreeTitle")]
		public virtual string CardThreeTitle => this.Value<string>(_publishedValueFallback, "cardThreeTitle");

		///<summary>
		/// Card Two - Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cardTwoDate")]
		public virtual string CardTwoDate => this.Value<string>(_publishedValueFallback, "cardTwoDate");

		///<summary>
		/// Card Two - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cardTwoImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CardTwoImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "cardTwoImage");

		///<summary>
		/// Card Two - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cardTwoTitle")]
		public virtual string CardTwoTitle => this.Value<string>(_publishedValueFallback, "cardTwoTitle");

		///<summary>
		/// Contact - Background Image One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBackgroundImageOne")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactBackgroundImageOne => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactBackgroundImageOne");

		///<summary>
		/// Contact - Background Image Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBackgroundImageTwo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactBackgroundImageTwo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactBackgroundImageTwo");

		///<summary>
		/// Contact - Box One Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxOneText")]
		public virtual string ContactBoxOneText => this.Value<string>(_publishedValueFallback, "contactBoxOneText");

		///<summary>
		/// Contact - Box One Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxOneTitle")]
		public virtual string ContactBoxOneTitle => this.Value<string>(_publishedValueFallback, "contactBoxOneTitle");

		///<summary>
		/// Contact - Box Three Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxThreeText")]
		public virtual string ContactBoxThreeText => this.Value<string>(_publishedValueFallback, "contactBoxThreeText");

		///<summary>
		/// Contact - Box Three Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxThreeTitle")]
		public virtual string ContactBoxThreeTitle => this.Value<string>(_publishedValueFallback, "contactBoxThreeTitle");

		///<summary>
		/// Contact - Box Two Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxTwoText")]
		public virtual string ContactBoxTwoText => this.Value<string>(_publishedValueFallback, "contactBoxTwoText");

		///<summary>
		/// Contact - Box Two Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxTwoTitle")]
		public virtual string ContactBoxTwoTitle => this.Value<string>(_publishedValueFallback, "contactBoxTwoTitle");

		///<summary>
		/// Contact - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactHeadline")]
		public virtual string ContactHeadline => this.Value<string>(_publishedValueFallback, "contactHeadline");

		///<summary>
		/// Contact - Main Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactMainImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactMainImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactMainImage");

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// Page Title - Breadcrumb Current Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleBreadcrumbCurrentText")]
		public virtual string PageTitleBreadcrumbCurrentText => this.Value<string>(_publishedValueFallback, "pageTitleBreadcrumbCurrentText");

		///<summary>
		/// Page Title - Breadcrumb Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleBreadcrumbText")]
		public virtual string PageTitleBreadcrumbText => this.Value<string>(_publishedValueFallback, "pageTitleBreadcrumbText");

		///<summary>
		/// Page Title - Breadcrumb Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleBreadcrumbTextTwo")]
		public virtual string PageTitleBreadcrumbTextTwo => this.Value<string>(_publishedValueFallback, "pageTitleBreadcrumbTextTwo");

		///<summary>
		/// Page Title - Breadcrumb Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleBreadcrumbUrl")]
		public virtual string PageTitleBreadcrumbUrl => this.Value<string>(_publishedValueFallback, "pageTitleBreadcrumbUrl");

		///<summary>
		/// Page Title - Breadcrumb Url Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleBreadcrumbUrlTwo")]
		public virtual string PageTitleBreadcrumbUrlTwo => this.Value<string>(_publishedValueFallback, "pageTitleBreadcrumbUrlTwo");

		///<summary>
		/// Page Title - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleHeadline")]
		public virtual string PageTitleHeadline => this.Value<string>(_publishedValueFallback, "pageTitleHeadline");

		///<summary>
		/// Tags - Text One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagsTextOne")]
		public virtual string TagsTextOne => this.Value<string>(_publishedValueFallback, "tagsTextOne");

		///<summary>
		/// Tags - Text Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagsTextThree")]
		public virtual string TagsTextThree => this.Value<string>(_publishedValueFallback, "tagsTextThree");

		///<summary>
		/// Tags - Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagsTextTwo")]
		public virtual string TagsTextTwo => this.Value<string>(_publishedValueFallback, "tagsTextTwo");

		///<summary>
		/// Tags - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagsTitle")]
		public virtual string TagsTitle => this.Value<string>(_publishedValueFallback, "tagsTitle");
	}
}
