//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Risk Management Page</summary>
	[PublishedModel("riskManagementPage")]
	public partial class RiskManagementPage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "riskManagementPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<RiskManagementPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public RiskManagementPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Article One - Bulleted Text One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleOneBulletedTextOne")]
		public virtual string ArticleOneBulletedTextOne => this.Value<string>(_publishedValueFallback, "articleOneBulletedTextOne");

		///<summary>
		/// Article One - Bulleted Text Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleOneBulletedTextThree")]
		public virtual string ArticleOneBulletedTextThree => this.Value<string>(_publishedValueFallback, "articleOneBulletedTextThree");

		///<summary>
		/// Article One - Bulleted Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleOneBulletedTextTwo")]
		public virtual string ArticleOneBulletedTextTwo => this.Value<string>(_publishedValueFallback, "articleOneBulletedTextTwo");

		///<summary>
		/// Article One - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleOneImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ArticleOneImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "articleOneImage");

		///<summary>
		/// Article One - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleOneTitle")]
		public virtual string ArticleOneTitle => this.Value<string>(_publishedValueFallback, "articleOneTitle");

		///<summary>
		/// Article Three - Bulleted Text Four
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleThreeBulletedTextFour")]
		public virtual string ArticleThreeBulletedTextFour => this.Value<string>(_publishedValueFallback, "articleThreeBulletedTextFour");

		///<summary>
		/// Article Three - Bulleted Text One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleThreeBulletedTextOne")]
		public virtual string ArticleThreeBulletedTextOne => this.Value<string>(_publishedValueFallback, "articleThreeBulletedTextOne");

		///<summary>
		/// Article Three - Bulleted Text Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleThreeBulletedTextThree")]
		public virtual string ArticleThreeBulletedTextThree => this.Value<string>(_publishedValueFallback, "articleThreeBulletedTextThree");

		///<summary>
		/// Article Three - Bulleted Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleThreeBulletedTextTwo")]
		public virtual string ArticleThreeBulletedTextTwo => this.Value<string>(_publishedValueFallback, "articleThreeBulletedTextTwo");

		///<summary>
		/// Article Three - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleThreeText")]
		public virtual string ArticleThreeText => this.Value<string>(_publishedValueFallback, "articleThreeText");

		///<summary>
		/// Article Three - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleThreeTitle")]
		public virtual string ArticleThreeTitle => this.Value<string>(_publishedValueFallback, "articleThreeTitle");

		///<summary>
		/// Article Two - Bulleted Text One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleTwoBulletedTextOne")]
		public virtual string ArticleTwoBulletedTextOne => this.Value<string>(_publishedValueFallback, "articleTwoBulletedTextOne");

		///<summary>
		/// Article Two - Bulleted Text Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleTwoBulletedTextThree")]
		public virtual string ArticleTwoBulletedTextThree => this.Value<string>(_publishedValueFallback, "articleTwoBulletedTextThree");

		///<summary>
		/// Article Two - Bulleted Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleTwoBulletedTextTwo")]
		public virtual string ArticleTwoBulletedTextTwo => this.Value<string>(_publishedValueFallback, "articleTwoBulletedTextTwo");

		///<summary>
		/// Article Two - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleTwoImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ArticleTwoImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "articleTwoImage");

		///<summary>
		/// Article Two - Text One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleTwoTextOne")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ArticleTwoTextOne => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "articleTwoTextOne");

		///<summary>
		/// Article Two - Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleTwoTextTwo")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ArticleTwoTextTwo => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "articleTwoTextTwo");

		///<summary>
		/// Article Two - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("articleTwoTitle")]
		public virtual string ArticleTwoTitle => this.Value<string>(_publishedValueFallback, "articleTwoTitle");

		///<summary>
		/// Aside Contact - Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideContactBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AsideContactBackgroundImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "asideContactBackgroundImage");

		///<summary>
		/// Aside Contact - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideContactText")]
		public virtual string AsideContactText => this.Value<string>(_publishedValueFallback, "asideContactText");

		///<summary>
		/// Aside Contact - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideContactTitle")]
		public virtual string AsideContactTitle => this.Value<string>(_publishedValueFallback, "asideContactTitle");

		///<summary>
		/// Aside - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideHeadline")]
		public virtual string AsideHeadline => this.Value<string>(_publishedValueFallback, "asideHeadline");

		///<summary>
		/// Aside - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AsideImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "asideImage");

		///<summary>
		/// Aside - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideText")]
		public virtual string AsideText => this.Value<string>(_publishedValueFallback, "asideText");

		///<summary>
		/// Contact - Background Image One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBackgroundImageOne")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactBackgroundImageOne => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactBackgroundImageOne");

		///<summary>
		/// Contact - Background Image Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBackgroundImageTwo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactBackgroundImageTwo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactBackgroundImageTwo");

		///<summary>
		/// Contact - Box One Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxOneText")]
		public virtual string ContactBoxOneText => this.Value<string>(_publishedValueFallback, "contactBoxOneText");

		///<summary>
		/// Contact - Box One Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxOneTitle")]
		public virtual string ContactBoxOneTitle => this.Value<string>(_publishedValueFallback, "contactBoxOneTitle");

		///<summary>
		/// Contact - Box Three Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxThreeText")]
		public virtual string ContactBoxThreeText => this.Value<string>(_publishedValueFallback, "contactBoxThreeText");

		///<summary>
		/// Contact - Box Three Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxThreeTitle")]
		public virtual string ContactBoxThreeTitle => this.Value<string>(_publishedValueFallback, "contactBoxThreeTitle");

		///<summary>
		/// Contact - Box Two Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxTwoText")]
		public virtual string ContactBoxTwoText => this.Value<string>(_publishedValueFallback, "contactBoxTwoText");

		///<summary>
		/// Contact - Box Two Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactBoxTwoTitle")]
		public virtual string ContactBoxTwoTitle => this.Value<string>(_publishedValueFallback, "contactBoxTwoTitle");

		///<summary>
		/// Contact - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactHeadline")]
		public virtual string ContactHeadline => this.Value<string>(_publishedValueFallback, "contactHeadline");

		///<summary>
		/// Contact - Main Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactMainImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactMainImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactMainImage");

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// Page Title - Breadcrumb Current Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleBreadcrumbCurrentText")]
		public virtual string PageTitleBreadcrumbCurrentText => this.Value<string>(_publishedValueFallback, "pageTitleBreadcrumbCurrentText");

		///<summary>
		/// Page Title - Breadcrumb Text One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleBreadcrumbTextOne")]
		public virtual string PageTitleBreadcrumbTextOne => this.Value<string>(_publishedValueFallback, "pageTitleBreadcrumbTextOne");

		///<summary>
		/// Page Title - Breadcrumb Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleBreadcrumbTextTwo")]
		public virtual string PageTitleBreadcrumbTextTwo => this.Value<string>(_publishedValueFallback, "pageTitleBreadcrumbTextTwo");

		///<summary>
		/// Page Title - Breadcrumb Url One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleBreadcrumbUrlOne")]
		public virtual string PageTitleBreadcrumbUrlOne => this.Value<string>(_publishedValueFallback, "pageTitleBreadcrumbUrlOne");

		///<summary>
		/// Page Title - Breadcrumb Url Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleBreadcrumbUrlTwo")]
		public virtual string PageTitleBreadcrumbUrlTwo => this.Value<string>(_publishedValueFallback, "pageTitleBreadcrumbUrlTwo");

		///<summary>
		/// Page Title - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleHeadline")]
		public virtual string PageTitleHeadline => this.Value<string>(_publishedValueFallback, "pageTitleHeadline");
	}
}
